var quotes =
[
    "Genius is one percent inspiration and ninety-nine percent perspiration.",
    "You can observe a lot just by watching.",
    "A house divided against itself cannot stand.",
    "Difficulties increase the nearer we get to the goal.",
    "Fate is in your hands and no one elses",
    "Be the chief but never the lord.",
    "Well begun is half done.",
    "Nothing happens unless first we dream.",
    "Life is a learning experience, only if you learn.",
    "Self-complacency is fatal to progress.",
    "Peace comes from within. Do not seek it without.",
    "What you give is what you get.",
    "We can only learn to love by loving.",
    "Life is change. Growth is optional. Choose wisely.",
    "You'll see it when you believe it.",
    "To lead people walk behind them.",
    "Today is the tomorrow we worried about yesterday.",
    "It's easier to see the mistakes on someone else's paper.",
    "Every man dies. Not every man really lives.",
    "Having nothing, nothing can he lose.",
    "A goal without a plan is just a wish.",
    "Genius is one percent inspiration and ninety-nine percent perspiration.",
    "You can observe a lot just by watching.",
    "A house divided against itself cannot stand.",
    "Difficulties increase the nearer we get to the goal.",
    "Fate is in your hands and no one elses",
    "Be the chief but never the lord.",
    "Nothing happens unless first we dream.",
	"Well begun is half done.",
	"Life is a learning experience, only if you learn.",
	"Self-complacency is fatal to progress.",
	"Peace comes from within. Do not seek it without.",
	"What you give is what you get.",
	"We can only learn to love by loving.",
	"Life is change. Growth is optional. Choose wisely.",
	"You'll see it when you believe it.",
	"Be as you wish to seem.",
	"To succeed, we must first believe that we can.",
	"Love is the flower you've got to let grow.",
	"Don't wait. The time will never be just right.",
	"One fails forward toward success.",
    "Time is the wisest counsellor of all.",
	"You give before you get.",
	"Wisdom begins in wonder.",
	"Without courage, wisdom bears no fruit.",
	"Change in all things is sweet.",
	"What you fear is that which requires action to overcome.",
	"The best teacher is experience learned from failures.",
	"When performance exceeds ambition, the overlap is called success.",
	"When deeds speak, words are nothing.",
	"Real magic in relationships means an absence of judgement of others.",
	"When performance exceeds ambition, the overlap is called success.",
	"I never think of the future. It comes soon enough.",
	"Skill to do comes of doing.",
	"Wisdom is the supreme part of happiness.",
	"I believe that every person is born with talent.",
	"Important principles may, and must, be inflexible.",
	"The undertaking of a new action brings new strength.",
	"I believe that every person is born with talent.",
	"The years teach much which the days never know.",
	"Our distrust is very expensive.",
	"All know the way; few actually walk it.",
	"Great talent finds happiness in execution.",
	"Faith in oneself is the best and safest course.",
	"Courage is going from failure to failure without losing enthusiasm.",
	"The two most powerful warriors are patience and time.",
	"Anticipate the difficult by managing the easy.",
	"Those who are free of resentful thoughts surely find peace.",
	"Talk doesn't cook rice.",
	"A short saying often contains much wisdom.",
	"The day is already blessed, find peace within it.",
	"It takes both sunshine and rain to make a rainbow.",
	"A beautiful thing is never perfect.",
    "Only do what your heart tells you.",
    "Life is movement-we breathe, we eat, we walk, we move!",
]

function newQuote() 
{
    var randomNumber = Math.floor(Math.random() * (quotes.length) );
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}